sudo: required
language: python
python:
  - "3.6"
git:
  depth: 3
services:
  - docker
stages:
  - test
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: test
      script:
        - pip install -r requirements.txt
        - pytest
    - stage: deploy
      script:
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        - docker build -t "$DOCKER_USERNAME"/docume_webapp:$TRAVIS_BUILD_NUMBER .
        - docker push "$DOCKER_USERNAME"/docume_webapp:$TRAVIS_BUILD_NUMBER
