sudo: required
language: python
python:
  - "3.6"
git:
  depth: 3
services:
  - docker
stages:
  - test
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: test
      script:
        - pip install -r requirements.txt
        - pytest
    - stage: deploy
      script:
        - ./docker_push_image.sh
