sudo: required
language: python
python:
  - "3.6"
git:
  depth: 3
services:
  - docker
stages:
  - test
  - name: deploy
    if: branch = master
test:
  install:
    - pip install -r requirements.txt
  provider:
    - script
  script:
    - pytest
deploy:
    provider:
      - script
    script:
      - docker_push_image.sh
